AllNode = NameRegex, FilterKey = "^(?!.*((?i)回国|校园|游戏|教育|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|群|GAME|TG|traffic|expire|netease)).*$"
HongKong = NameRegex, FilterKey = "^(?=.*((?i)🇭🇰|港|虚通|HK|Hong)).*$"
Taiwan = NameRegex, FilterKey = "^(?=.*((?i)🇹🇼|台|TW|Tai)).*$"
Japan = NameRegex, FilterKey = "^(?=.*((?i)🇯🇵|日|川日|东京|大阪|泉日|埼玉|JP|Japan)).*$"
Korea = NameRegex, FilterKey = "^(?=.*((?i)🇰🇷|韩|韓|首尔|KR|Korea)).*$"
American = NameRegex, FilterKey = "^(?=.*((?i)🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|UnitedStates)).*$"
Singapore = NameRegex, FilterKey = "^(?=.*((?i)🇸🇬|新加坡|狮|SG|Singapore)).*$"
Other = NameRegex, FilterKey = "^(?!.*((?i)🇭🇰|🇨🇳|🇯🇵|🇰🇷|🇸🇬|🇺🇸|netease|traffic|expire)).*$"
unblock = NameRegex, FilterKey = "(?i)(unblock|music|云音乐)"
