const path = require('node:path')
require('dotenv').config({ path: path.resolve(__dirname, '../.env.local') })
const ENV = require('node:process').env

const {
  SURGIO_UPLOAD_REGION,
  SURGIO_URL_BASE,
  SURGIP_UPLOAD_ACCESS_KEY_ID,
  SURGIP_UPLOAD_ACCESS_KEY_SECRET,
  SURGIP_UPLOAD_BUCKET,
  SURGIP_UPLOAD_PREFIX,
  PRIVATE_GIST_ID,
  PRIVATE_GIST_ID_COMPANY,
  MITM_CA_PASSPHRASE,
  MITM_CA_P12,
  CF_WIREGUARD_PUBLICK_KEY,
  CF_WIREGUARD_PRIVATE_KEY,
} = ENV

module.exports = {
  SURGIO_UPLOAD_REGION,
  SURGIO_URL_BASE,
  SURGIP_UPLOAD_ACCESS_KEY_ID,
  SURGIP_UPLOAD_ACCESS_KEY_SECRET,
  SURGIP_UPLOAD_BUCKET,
  SURGIP_UPLOAD_PREFIX,
  PRIVATE_GIST_ID,
  PRIVATE_GIST_ID_COMPANY,
  MITM_CA_PASSPHRASE,
  MITM_CA_P12,
  CF_WIREGUARD_PUBLICK_KEY,
  CF_WIREGUARD_PRIVATE_KEY,
}
