module.exports = {
  Proxy: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Proxy.png',
  Select: '🌀 Select',
  GCDN: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Cloudflare.png', // Global CDN
  CCDN: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Mainland.png', // China CDN
  Wifi: '👀 Wifi',
  Warp: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/warp.png',
  Auto: '🚦 Auto',
  Direct: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Direct.png',
  Reject: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Reject.png',
  Final: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Final.png',
  Download: '⬇️ Download',
  NeteaseMusic: '🎧 NeteaseMusic',
  Spotify: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Spotify.png',
  Reddit: '🤖 Reddit',
  Telegram: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Telegram.png',
  BiliBili: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Bilibili.png',
  AppStore: '🍎 AppStore',
  Apple: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Apple.png',
  Game: '🎮 Game',
  Google: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Google.png',
  GoogleDriver: '📂 Google Driver',
  GoogleVoice: '📞 GoogleVoice',
  Bing: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Bing.png',
  Teams: '🗣️ Teams',
  OneDrive: '📁 OneDrive',
  Microsoft: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Microsoft.png',
  Company: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/taipei101.png',
  Developer: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/github_01.png',
  OpenAI: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/OpenAI.png',
  Coze: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/Twoandz9/WYY.png',
  PikPak: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/softlyx/PikPak.png',
  TikTok: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Tiktok.png',
  DouYin: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Tiktok.png',
  Performance: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Pornhub.png',
  Emby: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Emby.png',
  Notion: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Notion.png',
  SpeedTest: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Speedtest.png',
  SubNodesSelect: '🏳️‍🌈 SubNodes-Select',
  HongKongSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/HK02.png',
  TaiWanSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/TW.png',
  JapanSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/JP.png',
  KoreaSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/KR.png',
  SingaporeSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/SG.png',
  AmericanSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/US.png',
  EuropeSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/UK.png',
  OtherSelect: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/TR.png',
  LowMagnification: 'https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Outside.png',
}
