module.exports = {
  Proxy: '🐷 Proxy',
  Select: '🌀 Select',
  GCDN: '🚀 GCDN', // Global CDN
  CCDN: '🚀 CCDN', // China CDN
  Wifi: '👀 Wifi',
  Warp: '☁️ Warp',
  Auto: '🚦 Auto',
  Direct: '🎯 DIRECT',
  Reject: '🛑 REJECT',
  Final: '🐟 Final',
  Download: '⬇️ Download',
  NeteaseMusic: '🎧 NeteaseMusic',
  Spotify: '🎶 Spotify',
  Reddit: '🤖 Reddit',
  Telegram: '✈️ Telegram',
  BiliBili: '📺 BiliBili',
  AppStore: '🍎 AppStore',
  Apple: '🍎 Apple',
  Game: '🎮 Game',
  Google: '🔍 Google',
  GoogleDriver: '📂 Google Driver',
  GoogleVoice: '📞 GoogleVoice',
  Bing: '🔎 Bing',
  Teams: '🗣️ Teams',
  OneDrive: '📁 OneDrive',
  Microsoft: 'Ⓜ️ Microsoft',
  Company: '💼 Company',
  Developer: '👨‍💻 Developer',
  OpenAI: '🎉 OpenAI',
  Coze: '👽 Coze',
  PikPak: '📂 PikPak',
  TikTok: '📽 TikTok',
  DouYin: '📽 DouYin',
  Performance: '💪 Performance',
  Emby: '🎞 Emby',
  Notion: '📖 Notion',
  SpeedTest: '🚀 SpeedTest',
  SubNodesSelect: '🏳️‍🌈 SubNodes',
  HongKongSelect: '🇭🇰 HongKong',
  TaiWanSelect: '🇨🇳 Taiwan',
  JapanSelect: '🇯🇵 Japan',
  KoreaSelect: '🇰🇷 Korea',
  SingaporeSelect: '🇸🇬 Singapore',
  AmericanSelect: '🇺🇸 American',
  EuropeSelect: '🇪🇺 Europe',
  OtherSelect: '🏴‍☠️ Other-Area',
}
